import assert from "node:assert/strict";
import fs from "node:fs/promises";
import { createStaticServer } from "./static-server.js";

const server = createStaticServer();

await new Promise((resolve) => {
  server.listen(0, "127.0.0.1", resolve);
});

const address = server.address();
const baseUrl = `http://127.0.0.1:${address.port}`;

try {
  const indexResponse = await fetch(`${baseUrl}/`);
  const indexHtml = await indexResponse.text();

  assert.equal(indexResponse.status, 200);
  assert.ok(indexHtml.includes("RiffRush MVP Shell"));

  const appResponse = await fetch(`${baseUrl}/app.js`);
  const appSource = await appResponse.text();
  const stylesSource = await fs.readFile(new URL("../public/styles.css", import.meta.url), "utf8");

  assert.equal(appResponse.status, 200);
  assert.ok(appSource.includes("loadTrainings"));
  assert.ok(appSource.includes("/users/${encodeURIComponent(userId)}/trainings"));
  assert.ok(indexHtml.includes("Run native preflight"));
  assert.ok(indexHtml.includes("Apply recommendation"));
  assert.ok(indexHtml.includes("Auto-apply recommended capture path on session start"));
  assert.ok(indexHtml.includes("Capture diagnostics"));
  assert.ok(indexHtml.includes("Technical comparison"));
  assert.ok(indexHtml.includes("Capture preferences"));
  assert.ok(indexHtml.includes("Recent capture overrides"));
  assert.ok(indexHtml.includes("Setup recommendation feedback"));
  assert.ok(indexHtml.includes("Targeted practice"));
  assert.ok(indexHtml.includes("No targeted practice recommendation yet."));
  assert.ok(indexHtml.includes("Session tempo BPM"));
  assert.ok(indexHtml.includes("Practice scope"));
  assert.ok(indexHtml.includes("Loop section"));
  assert.ok(indexHtml.includes("Loop repetitions"));
  assert.ok(indexHtml.includes("Tempo step BPM"));
  assert.ok(indexHtml.includes("Apply practice preset"));
  assert.ok(indexHtml.includes("No newly unlocked training yet."));
  assert.ok(indexHtml.includes("Select unlocked training and prefill session"));
  assert.ok(indexHtml.includes("Start unlocked training now"));
  assert.ok(indexHtml.includes("Unlock onboarding will appear after the next newly unlocked training."));
    assert.ok(indexHtml.includes("Session completion recap will appear after the next finished session."));
    assert.ok(indexHtml.includes("Dominant confidence signal will appear after the next finished session."));
    assert.ok(indexHtml.includes("Checkpoint recap cards will appear after the next finished session."));
    assert.ok(indexHtml.includes("Checkpoint path summary cards will appear after the next finished sessions."));
    assert.ok(indexHtml.includes("Checkpoint path handoff will appear after the next successful path action."));
    assert.ok(indexHtml.includes("Show all checkpoint paths"));
    assert.ok(indexHtml.includes("Checkpoint history filter"));
  assert.ok(indexHtml.includes("All checkpoints"));
  assert.ok(indexHtml.includes("Unlock"));
  assert.ok(indexHtml.includes("Recovery"));
  assert.ok(indexHtml.includes("Return"));
  assert.ok(indexHtml.includes("Promotion"));
  assert.ok(indexHtml.includes("Mastery"));
  assert.ok(indexHtml.includes("Checkpoint history snapshots will appear after the next finished sessions."));
  assert.ok(indexHtml.includes("progression-checkpoint-detail-badges"));
  assert.ok(indexHtml.includes("Checkpoint detail will appear after you select a history snapshot."));
  assert.ok(indexHtml.includes("Dominant confidence signal will guide the next action after the next finished session."));
  assert.ok(indexHtml.includes("Checkpoint-driven next action will appear after the next finished session."));
  assert.ok(indexHtml.includes("Follow checkpoint action"));
  assert.ok(indexHtml.includes("Progression timeline will appear after the next finished session."));
  assert.ok(indexHtml.includes("progression-desktop-layout"));
  assert.ok(indexHtml.includes("progression-overview-column"));
  assert.ok(indexHtml.includes("progression-workbench-column"));
  assert.ok(indexHtml.includes("progression-history-column"));
  assert.ok(indexHtml.includes("progression-action-column"));
  assert.ok(indexHtml.includes("Checkpoint workspace"));
  assert.ok(indexHtml.includes("History and timeline"));
  assert.ok(indexHtml.includes("Action rail"));
  assert.ok(indexHtml.includes("Detail and next step"));
  assert.ok(indexHtml.includes("Current checkpoint"));
  assert.ok(indexHtml.includes("Guided next step"));
  assert.ok(indexHtml.includes("What now"));
  assert.ok(indexHtml.includes("Why now"));
  assert.ok(indexHtml.includes("Execution state will appear after the next finished session."));
  assert.ok(indexHtml.includes("Action execution hint will appear after the next finished session."));
  assert.ok(indexHtml.includes("Waiting for guided action result."));
  assert.ok(indexHtml.includes("Waiting for next focus."));
  assert.ok(indexHtml.includes("What happened"));
  assert.ok(indexHtml.includes("Where now"));
  assert.ok(indexHtml.includes("progression-next-action-feedback-badge-row"));
  assert.ok(indexHtml.includes("progression-next-action-focus-badge-row"));
  assert.ok(indexHtml.includes("No setup recommendation feedback recorded yet."));
  assert.ok(indexHtml.includes("Apply filters"));
  assert.ok(indexHtml.includes("Clear filters"));
  assert.ok(indexHtml.includes("Sort paths"));
  assert.ok(indexHtml.includes("Sort direction"));
  assert.ok(indexHtml.includes("Export JSON"));
  assert.ok(indexHtml.includes("Export CSV"));
  assert.ok(indexHtml.includes("Most problematic path"));
  assert.ok(indexHtml.includes("Per-device recommendations"));
  assert.ok(indexHtml.includes("Selected device diagnostics"));
  assert.ok(indexHtml.includes("Runtime issue breakdown"));
  assert.ok(indexHtml.includes("Load device detail"));
  assert.ok(appSource.includes("Targets: ${training.targetSequence?.map((target) =>"));
  assert.ok(indexHtml.includes("Recommended capture path will appear"));
  assert.ok(indexHtml.includes("No problematic paths ranked yet."));
  assert.ok(indexHtml.includes("No per-device recommendations yet."));
  assert.ok(indexHtml.includes("No device diagnostics loaded yet."));
  assert.ok(indexHtml.includes("No runtime issue breakdown available yet."));
  assert.ok(indexHtml.includes("No capture overrides recorded yet."));
  assert.ok(indexHtml.includes("recommended capture paths"));
  assert.ok(indexHtml.includes("Load dashboard data to unlock recommended capture paths."));
  assert.ok(appSource.includes("renderSessionDiagnostics"));
  assert.ok(appSource.includes("getVerificationHoldTechnicalFallbackRecommendation"));
  assert.ok(appSource.includes("applyVerificationHoldTechnicalFallbackRecommendation"));
  assert.ok(appSource.includes("maybeAutoApplyCaptureRecommendation"));
  assert.ok(appSource.includes("Verification hold suggests a safer native path"));
  assert.ok(appSource.includes("verification-hold fallback"));
  assert.ok(appSource.includes("formatPrimarySetupRecommendation"));
  assert.ok(appSource.includes("Next technical step:"));
  assert.ok(appSource.includes("Technical focus:"));
  assert.ok(appSource.includes("Max chunk gap"));
  assert.ok(appSource.includes("Low signal"));
  assert.ok(appSource.includes("Tempo ${result.scoreBreakdown.tempoBpm} BPM"));
  assert.ok(appSource.includes("matched ${result.scoreBreakdown.matchedTargetCount}"));
  assert.ok(appSource.includes("sustain hits ${result.scoreBreakdown.sustainHits ?? 0}"));
  assert.ok(appSource.includes("release hits ${result.scoreBreakdown.releaseHits ?? 0}"));
  assert.ok(appSource.includes("missed targets ${result.scoreBreakdown.missedTargetCount ?? 0}"));
  assert.ok(appSource.includes("ghost notes ${result.scoreBreakdown.ghostNoteCount ?? 0}"));
  assert.ok(appSource.includes("max combo ${result.scoreBreakdown.maxCombo ?? 0}"));
  assert.ok(appSource.includes("multiplier peak x${result.scoreBreakdown.multiplierPeak ?? 1}"));
  assert.ok(appSource.includes("grade ${result.rating.grade} (${result.rating.label}), clear ${result.rating.clearType}, performance ${result.rating.performanceScore}"));
  assert.ok(appSource.includes("Coach summary: ${result.feedback.summary}"));
  assert.ok(appSource.includes("Hints: ${result.feedback.coachHints.map((hint) => `${hint.title} [${hint.severity}]`).join(\" | \")}"));
  assert.ok(appSource.includes("Repeat current training"));
  assert.ok(appSource.includes("Section focus: ${dashboard.targetedPractice.recommendedSectionLabel}"));
  assert.ok(appSource.includes("Recovery path: start from ${dashboard.targetedPractice.practiceSectionLabel}"));
  assert.ok(appSource.includes("Recovery unlocked: return to ${dashboard.targetedPractice.recoveryGoalTrainingTitle}"));
  assert.ok(appSource.includes("switch to ${dashboard.targetedPractice.recoveryTrainingTitle} [${dashboard.targetedPractice.recoveryTrainingDifficulty}]"));
  assert.ok(appSource.includes("Recovery result"));
  assert.ok(appSource.includes("Recovery milestone: ${dashboard.targetedPractice.recoveryMilestone.stableSessionCount}/${dashboard.targetedPractice.recoveryMilestone.requiredStableSessions} stable session(s) collected for the return path."));
  assert.ok(appSource.includes("Return milestone: ${dashboard.targetedPractice.returnMilestone.stableReturnSessionCount}/${dashboard.targetedPractice.returnMilestone.requiredStableReturnSessions} stable return session(s) collected for the goal chart."));
  assert.ok(appSource.includes("Return ramp: ${dashboard.targetedPractice.returnRamp.mode} -> ${dashboard.targetedPractice.returnRamp.targetTempoBpm} BPM"));
  assert.ok(appSource.includes("Chart expansion: ${dashboard.targetedPractice.chartExpansion.mode} from ${dashboard.targetedPractice.chartExpansion.sourceSectionLabel} -> ${dashboard.targetedPractice.chartExpansion.targetScope} at ${dashboard.targetedPractice.chartExpansion.targetTempoBpm} BPM."));
  assert.ok(appSource.includes("Full-chart reintegration: ${dashboard.targetedPractice.fullChartReintegrationMilestone.stableFullChartSessionCount}/${dashboard.targetedPractice.fullChartReintegrationMilestone.requiredStableFullChartSessions} stable full-chart session(s) collected after expansion."));
  assert.ok(appSource.includes("Full-chart reintegration ramp: ${dashboard.targetedPractice.fullChartReintegrationRamp.mode} -> ${dashboard.targetedPractice.fullChartReintegrationRamp.targetTempoBpm} BPM."));
  assert.ok(appSource.includes("Promotion route: switch to ${dashboard.targetedPractice.promotionTargetTrainingTitle} [${dashboard.targetedPractice.promotionTargetDifficulty}] at ${dashboard.targetedPractice.suggestedTempoBpm} BPM."));
  assert.ok(appSource.includes("Promotion landing: ${dashboard.targetedPractice.promotionLandingMilestone.stablePromotionLandingSessionCount}/${dashboard.targetedPractice.promotionLandingMilestone.requiredStablePromotionLandingSessions} stable promoted session(s) collected on ${dashboard.targetedPractice.recommendedTrainingTitle}."));
  assert.ok(appSource.includes("Promotion ramp: ${dashboard.targetedPractice.promotionRamp.mode} -> ${dashboard.targetedPractice.promotionRamp.targetTempoBpm} BPM"));
  assert.ok(appSource.includes("Promotion ramp milestone: ${dashboard.targetedPractice.promotionRampMilestone.stablePromotionRampSessionCount}/${dashboard.targetedPractice.promotionRampMilestone.requiredStablePromotionRampSessions} stable ramp session(s) collected on ${dashboard.targetedPractice.recommendedTrainingTitle}."));
  assert.ok(appSource.includes("Promotion track: ${dashboard.targetedPractice.promotionTrackMilestone.confirmedRampTierCount}/${dashboard.targetedPractice.promotionTrackMilestone.requiredConfirmedRampTiers} confirmed ramp tier(s) completed on ${dashboard.targetedPractice.promotionTargetTrainingTitle ?? dashboard.targetedPractice.recommendedTrainingTitle}."));
  assert.ok(appSource.includes("Promotion graduation: switch to ${dashboard.targetedPractice.promotionGraduation.targetTrainingTitle} [${dashboard.targetedPractice.promotionGraduation.targetTrainingDifficulty}] at ${dashboard.targetedPractice.promotionGraduation.targetTempoBpm} BPM."));
  assert.ok(appSource.includes("Promotion re-entry: ${dashboard.targetedPractice.promotionReentryMilestone.stablePromotionReentrySessionCount}/${dashboard.targetedPractice.promotionReentryMilestone.requiredStablePromotionReentrySessions} stable re-entry session(s) collected on ${dashboard.targetedPractice.recommendedTrainingTitle}."));
  assert.ok(appSource.includes("Promotion chain milestone: ${dashboard.targetedPractice.promotionChainMilestone.stablePromotionChainSessionCount}/${dashboard.targetedPractice.promotionChainMilestone.requiredStablePromotionChainSessions} stable chain session(s) collected on ${dashboard.targetedPractice.recommendedTrainingTitle}."));
  assert.ok(appSource.includes("Promotion chain: ${dashboard.targetedPractice.promotionChain.mode} -> ${dashboard.targetedPractice.promotionChain.targetTempoBpm} BPM from ${dashboard.targetedPractice.promotionChain.baseTempoBpm} BPM."));
  assert.ok(appSource.includes("Primary focus: ${dashboard.targetedPractice.primaryFocus.title} [${dashboard.targetedPractice.primaryFocus.severity}]"));
  assert.ok(appSource.includes("Practice preset: ${result.practicePreset.scope === \"section-loop\""));
  assert.ok(appSource.includes("result.practicePreset.loopRepetitionCount ? `, ${result.practicePreset.loopRepetitionCount} rep(s)`"));
  assert.ok(appSource.includes("result.practicePreset.loopTempoStepBpm ? `, +${result.practicePreset.loopTempoStepBpm} BPM per rep`"));
  assert.ok(appSource.includes("formatMasteryGateSummary"));
  assert.ok(appSource.includes("formatAdaptiveExecutionSummary"));
  assert.ok(appSource.includes("Mastery gate: ${masteryGate.status}, passed ${masteryGate.passedRepetitionCount}/${masteryGate.totalRepetitionCount}"));
  assert.ok(appSource.includes("Adaptive execution: ${adaptiveExecution.mode}, completed ${adaptiveExecution.completedRepetitionCount}/${adaptiveExecution.plannedRepetitionCount} rep(s)"));
  assert.ok(appSource.includes("Retry plan: ${adaptiveExecution.retryPlan.strategy} @ ${adaptiveExecution.retryPlan.tempoBpm} BPM"));
  assert.ok(appSource.includes("Repetition results: ${formatPracticeRepetitionSummary(result.practicePreset.repetitions)}"));
  assert.ok(appSource.includes("Sections: ${result.sectionBreakdown.map((section) =>"));
  assert.ok(appSource.includes("avg hold coverage ${result.scoreBreakdown.averageHoldCoverage ?? 0}"));
  assert.ok(appSource.includes("avg release overshoot ${result.scoreBreakdown.averageReleaseOvershootMs ?? 0} ms"));
  assert.ok(appSource.includes("\"Ghost note\""));
  assert.ok(appSource.includes("\"Missed target\""));
  assert.ok(appSource.includes("combo ${message.payload.comboCount}, multiplier x${message.payload.comboMultiplier}"));
  assert.ok(appSource.includes("[count ${message.payload.comboCount}, x${message.payload.comboMultiplier}${message.payload.comboBroken ? \", break\" : \"\"}]"));
  assert.ok(appSource.includes("received string"));
  assert.ok(appSource.includes("bar ${message.payload.measureNumber}, beat ${message.payload.beatNumber}"));
  assert.ok(appSource.includes("timing ${message.payload.timingClass}"));
  assert.ok(appSource.includes("hold ${message.payload.sustainHit ? \"ok\" : message.payload.releasedEarly ? \"early-release\" : \"miss\"}"));
  assert.ok(appSource.includes("release ${message.payload.releaseHit ? \"ok\" : message.payload.overheld ? `overheld by ${message.payload.releaseOvershootMs} ms` : message.payload.releasedEarly ? \"not-reached\" : \"miss\"}"));
  assert.ok(appSource.includes("Chart: ${training.chartSummary"));
  assert.ok(appSource.includes("Sections: ${training.chart?.sections"));
  assert.ok(appSource.includes("renderDiagnosticsReport"));
  assert.ok(appSource.includes("renderDashboard"));
  assert.ok(appSource.includes("Latest unlocks"));
  assert.ok(appSource.includes("No new unlocks"));
  assert.ok(appSource.includes("renderUnlockCelebration"));
  assert.ok(appSource.includes("renderUnlockOnboardingHandoff"));
  assert.ok(appSource.includes("renderSessionCompletionRecap"));
  assert.ok(appSource.includes("buildGuidedNextActionStatusMessage"));
  assert.ok(appSource.includes("buildProgressionNextActionExecutionHint"));
  assert.ok(appSource.includes("buildProgressionNextActionExecutionState"));
  assert.ok(appSource.includes("buildProgressionActionHandoff"));
  assert.ok(appSource.includes("buildProgressionActionHandoffMessage"));
  assert.ok(appSource.includes("buildProgressionNextActionFeedbackMessage"));
  assert.ok(appSource.includes("buildProgressionNextActionFeedbackBadge"));
  assert.ok(appSource.includes("buildProgressionActionFocusBadge"));
  assert.ok(appSource.includes("buildProgressionNextActionFeedback"));
  assert.ok(appSource.includes("syncProgressionNextActionFeedback"));
  assert.ok(appSource.includes("applyProgressionNextActionHandoffState"));
  assert.ok(appSource.includes("renderProgressionNextActionExecutionState"));
  assert.ok(appSource.includes("renderProgressionNextActionFeedback"));
  assert.ok(appSource.includes("getProgressionNextActionStatusVariant"));
  assert.ok(appSource.includes("Ready to run"));
  assert.ok(appSource.includes("Prepare first"));
  assert.ok(appSource.includes("Blocked"));
  assert.ok(appSource.includes("Execution state"));
  assert.ok(appSource.includes("Blocked by setup"));
  assert.ok(appSource.includes("Preset applied"));
  assert.ok(appSource.includes("Launch started"));
  assert.ok(appSource.includes("Launch blocked"));
  assert.ok(appSource.includes("Waiting for next focus."));
  assert.ok(appSource.includes("Now active for the launched session."));
  assert.ok(appSource.includes("Now active for the prepared checkpoint."));
  assert.ok(appSource.includes("Review the current setup."));
  assert.ok(appSource.includes("Session is running."));
  assert.ok(appSource.includes("Start did not complete."));
  assert.ok(appSource.includes("Session status"));
  assert.ok(appSource.includes("Current checkpoint"));
  assert.ok(appSource.includes("compatibleNextActionKeys"));
  assert.ok(appSource.includes("Runs immediately from the current desktop session form."));
  assert.ok(appSource.includes("Updates the desktop session form with the guided preset before start."));
  assert.ok(appSource.includes("Support: ${support.join(\" | \")}."));
  assert.ok(appSource.includes("Diff aligned"));
  assert.ok(appSource.includes("buildCheckpointRecapCards"));
  assert.ok(appSource.includes("renderCheckpointRecapCards"));
  assert.ok(appSource.includes("createCheckpointSnapshotRecord"));
  assert.ok(appSource.includes("recordCheckpointSnapshot"));
  assert.ok(appSource.includes("formatCheckpointHistoryFilterLabel"));
  assert.ok(appSource.includes("formatCheckpointHistoryGroupLabel"));
  assert.ok(appSource.includes("resolvePrimaryCheckpointPathType"));
  assert.ok(appSource.includes("getFilteredCheckpointSnapshots"));
  assert.ok(appSource.includes("groupCheckpointSnapshotsByType"));
  assert.ok(appSource.includes("buildCheckpointPathSummaryCards"));
  assert.ok(appSource.includes("getCheckpointPathActionBaseHint"));
  assert.ok(appSource.includes("formatCheckpointPathActionHint"));
    assert.ok(appSource.includes("renderCheckpointPathAction"));
    assert.ok(appSource.includes("renderCheckpointPathActionFeedback"));
    assert.ok(appSource.includes("buildCheckpointPathActionFeedback"));
    assert.ok(appSource.includes("buildCheckpointPathHandoff"));
    assert.ok(appSource.includes("renderCheckpointPathHandoffStatus"));
    assert.ok(appSource.includes("renderCheckpointPathCollapseToggle"));
    assert.ok(appSource.includes("focusCheckpointPathHandoff"));
    assert.ok(appSource.includes("renderCheckpointPathSummaryCards"));
  assert.ok(appSource.includes("activateCheckpointPath"));
  assert.ok(appSource.includes("syncSelectedCheckpointSnapshot"));
  assert.ok(appSource.includes("getStickyCheckpointPathType"));
    assert.ok(appSource.includes("getStickyCheckpointPathLabel"));
    assert.ok(appSource.includes("buildCheckpointPathContextText"));
    assert.ok(appSource.includes("buildStickyCheckpointDetailPrefix"));
    assert.ok(appSource.includes("findTrainingSectionLabel"));
    assert.ok(appSource.includes("buildTrainingSessionPresetPreview"));
    assert.ok(appSource.includes("buildCheckpointPathSessionPresetPreview"));
    assert.ok(appSource.includes("buildCurrentSessionPresetPreview"));
    assert.ok(appSource.includes("buildSessionPresetDiff"));
    assert.ok(appSource.includes("buildCheckpointPathPresetConfidence"));
    assert.ok(appSource.includes("assessCheckpointSnapshotConfidence"));
    assert.ok(appSource.includes("buildCheckpointPathConfidenceHistory"));
    assert.ok(appSource.includes("buildCheckpointConfidenceHistorySummary"));
    assert.ok(appSource.includes("buildCheckpointPathConfidenceRecap"));
    assert.ok(appSource.includes("buildCheckpointConfidenceRecapSummary"));
    assert.ok(appSource.includes("buildCheckpointConfidenceReason"));
    assert.ok(appSource.includes("getCheckpointConfidenceReasonLabel"));
  assert.ok(appSource.includes("buildCheckpointWaitingMessage"));
  assert.ok(appSource.includes("buildCheckpointHistoryEmptyMessage"));
  assert.ok(appSource.includes("buildCheckpointDetailEmptyMessage"));
  assert.ok(appSource.includes("resetStatusCardClasses"));
  assert.ok(appSource.includes("getCheckpointFlowStatusMeta"));
  assert.ok(appSource.includes("getCheckpointFlowStatusInteractionState"));
  assert.ok(appSource.includes("buildCheckpointFlowStatusContent"));
  assert.ok(appSource.includes("truncateCheckpointFlowStatusText"));
  assert.ok(appSource.includes("compactCheckpointFlowStatusMessage"));
  assert.ok(appSource.includes("buildCheckpointFlowStatusStateLabel"));
  assert.ok(appSource.includes("buildCheckpointFlowStatusSourceMeta"));
  assert.ok(appSource.includes("getCheckpointFlowStatusSourceTone"));
  assert.ok(appSource.includes('phase: "spotlight"'));
  assert.ok(appSource.includes('phase: "waiting"'));
  assert.ok(appSource.includes('phase: "active"'));
  assert.ok(appSource.includes("getCheckpointFlowStatusStateTone"));
  assert.ok(appSource.includes("setCheckpointFlowStatus"));
  assert.ok(appSource.includes("getCheckpointFlowStatusElement"));
  assert.ok(appSource.includes("focusCheckpointFlowStatusCard"));
  assert.ok(appSource.includes('target.classList.add(content.note ? "has-note" : "no-note")'));
  assert.ok(appSource.includes('title="${escapeHtml(sourceMeta.label)}"'));
  assert.ok(appSource.includes('aria-label="${escapeHtml(sourceMeta.label)}"'));
  assert.ok(appSource.includes('title="${escapeHtml(content.note)}"'));
  assert.ok(appSource.includes('aria-label="${escapeHtml(content.note)}"'));
    assert.ok(appSource.includes("buildCheckpointConfidenceReasonGroup"));
    assert.ok(appSource.includes("buildDominantCheckpointConfidenceReasonGroup"));
    assert.ok(appSource.includes("buildDominantCheckpointConfidenceSignalStatus"));
    assert.ok(appSource.includes("renderDominantCheckpointConfidenceSignalStatuses"));
    assert.ok(appSource.includes("Dominant confidence signal"));
    assert.ok(appSource.includes("Dominant confidence:"));
    assert.ok(appSource.includes("Next action follows "));
    assert.ok(appSource.includes("buildCheckpointPathAutoFocus"));
    assert.ok(appSource.includes("applyCheckpointPathAutoFocusState"));
    assert.ok(appSource.includes("focusCheckpointPathAutoFocus"));
    assert.ok(appSource.includes("activateCheckpointConfidenceEntry"));
    assert.ok(appSource.includes("renderCheckpointHistorySnapshots"));
  assert.ok(appSource.includes("renderCheckpointHistoryDetail"));
  assert.ok(appSource.includes("dashboardPayload.data.checkpointHistorySnapshots"));
  assert.ok(appSource.includes("No ${formatCheckpointHistoryFilterLabel(activeFilter)} snapshots recorded yet."));
  assert.ok(appSource.includes("snapshot.type === activeFilter"));
  assert.ok(appSource.includes("data-checkpoint-path-type"));
  assert.ok(appSource.includes("data-checkpoint-path-action=\"run\""));
  assert.ok(appSource.includes("data-checkpoint-session-id"));
  assert.ok(appSource.includes("Training: ${detail.trainingTitle ?? selectedSnapshot.trainingTitle ?? selectedSnapshot.trainingId}"));
  assert.ok(appSource.includes("Reason: ${detail.reason}"));
  assert.ok(appSource.includes("Unlock path"));
  assert.ok(appSource.includes("Recovery path"));
  assert.ok(appSource.includes("Return path"));
  assert.ok(appSource.includes("Promotion path"));
  assert.ok(appSource.includes("Mastery path"));
  assert.ok(appSource.includes("snapshot(s)"));
  assert.ok(appSource.includes("Primary now"));
  assert.ok(appSource.includes("card.isPrimary"));
  assert.ok(appSource.includes("elements.progressionCheckpointFilter.value = nextFilter"));
  assert.ok(appSource.includes("Latest checkpoint:"));
  assert.ok(appSource.includes("Current status:"));
  assert.ok(appSource.includes("Suggested action:"));
  assert.ok(appSource.includes("actionLabel"));
    assert.ok(appSource.includes("actionDisabled"));
    assert.ok(appSource.includes("checkpointPathActionFeedback"));
    assert.ok(appSource.includes("checkpointPathHandoff"));
    assert.ok(appSource.includes("checkpointPathCollapse"));
    assert.ok(appSource.includes("Path action applied:"));
    assert.ok(appSource.includes("Path action attempted to start a session"));
    assert.ok(appSource.includes("Handoff complete: session started from this path."));
    assert.ok(appSource.includes("Handoff complete: session form updated for this path. Current checkpoint is now the active focus."));
  assert.ok(appSource.includes("Sticky focus"));
    assert.ok(appSource.includes("Path focus"));
    assert.ok(appSource.includes("Background path"));
    assert.ok(appSource.includes("Background status:"));
    assert.ok(appSource.includes("renderCheckpointPathPresetPreview"));
    assert.ok(appSource.includes("Preset preview"));
    assert.ok(appSource.includes("Preset confidence"));
    assert.ok(appSource.includes("Confidence history"));
    assert.ok(appSource.includes("Confidence recap"));
    assert.ok(appSource.includes("Reason ${truncateCheckpointFlowStatusText(confidenceReason.label, 44)}"));
    assert.ok(appSource.includes("Confidence group"));
    assert.ok(appSource.includes("Why confidence improved"));
    assert.ok(appSource.includes("Why confidence dropped"));
    assert.ok(appSource.includes("Why confidence stayed steady"));
    assert.ok(appSource.includes("Unlock signal"));
    assert.ok(appSource.includes("Recovery stability"));
    assert.ok(appSource.includes("Return validation"));
    assert.ok(appSource.includes("Promotion proof"));
    assert.ok(appSource.includes("Mastery proof"));
    assert.ok(appSource.includes("Dominant signal for this session."));
    assert.ok(appSource.includes("Supporting signal on this route."));
    assert.ok(appSource.includes("Supporting signal in this recap."));
    assert.ok(appSource.includes("Dominant confidence signal:"));
    assert.ok(appSource.includes("Next action follows the dominant confidence signal:"));
    assert.ok(appSource.includes("getCheckpointConfidenceActionBias"));
    assert.ok(appSource.includes("improved from"));
    assert.ok(appSource.includes("stayed at"));
    assert.ok(appSource.includes("dropped from"));
    assert.ok(appSource.includes("Recent confidence improved, so this path is ready to push forward."));
    assert.ok(appSource.includes("Recent confidence dropped, so review the preset before launching."));
    assert.ok(appSource.includes("Confidence dropped on the latest session, so review the preset carefully."));
    assert.ok(appSource.includes("Checkpoint auto-focus"));
    assert.ok(appSource.includes("confidence improved, so focus moved to the active path summary"));
    assert.ok(appSource.includes("confidence dropped, so focus moved to checkpoint detail"));
    assert.ok(appSource.includes("Confidence trend is"));
    assert.ok(appSource.includes("single-snapshot"));
    assert.ok(appSource.includes("data-checkpoint-confidence-session-id"));
    assert.ok(appSource.includes("data-checkpoint-confidence-path-type"));
    assert.ok(appSource.includes("freshly unlocked training"));
    assert.ok(appSource.includes("heuristic recommendation"));
    assert.ok(appSource.includes("Preset diff"));
    assert.ok(appSource.includes("session form already matches this path"));
    assert.ok(appSource.includes("Training:"));
    assert.ok(appSource.includes("Tempo:"));
    assert.ok(appSource.includes("unlock-targeted"));
    assert.ok(appSource.includes("unlock-default"));
    assert.ok(appSource.includes("guided"));
    assert.ok(appSource.includes("All checkpoint paths visible"));
    assert.ok(appSource.includes("resume the recovery route now"));
  assert.ok(appSource.includes("return to the goal chart now"));
  assert.ok(appSource.includes("continue the promotion route now"));
  assert.ok(appSource.includes("maintain the mastery route now"));
  assert.ok(appSource.includes("select the unlocked training and prefill the session"));
  assert.ok(appSource.includes("buildSessionCompletionRecap"));
    assert.ok(appSource.includes("buildCheckpointRecapCardEmphasis"));
    assert.ok(appSource.includes("getCheckpointConfidenceTrendMeta"));
    assert.ok(appSource.includes("pathContext"));
  assert.ok(appSource.includes("confidenceRecap"));
  assert.ok(appSource.includes("This recap is reinforced by an improving confidence signal."));
  assert.ok(appSource.includes("This recap is being handled more cautiously because confidence dropped."));
  assert.ok(appSource.includes("This recap is supported by a steady confidence signal."));
  assert.ok(appSource.includes("checkpoint-recap-confidence-reason"));
  assert.ok(appSource.includes("checkpoint-recap-confidence-group"));
  assert.ok(appSource.includes("createTargetedPracticeSnapshot"));
  assert.ok(appSource.includes("renderProgressionTimeline"));
  assert.ok(appSource.includes("buildProgressionTimelineEntries"));
  assert.ok(appSource.includes("Path focus"));
  assert.ok(appSource.includes("createCheckpointBadges"));
  assert.ok(appSource.includes("renderCheckpointBadgeRow"));
  assert.ok(appSource.includes("getProgressionNextAction"));
  assert.ok(appSource.includes("getCheckpointActionCopy"));
  assert.ok(appSource.includes("renderProgressionNextAction"));
  assert.ok(appSource.includes("runProgressionNextAction"));
  assert.ok(appSource.includes("getLatestUnlockedTrainingTransitionEntry"));
  assert.ok(appSource.includes("canStartLatestUnlockedTraining"));
  assert.ok(appSource.includes("selectLatestUnlockedTraining"));
  assert.ok(appSource.includes("startLatestUnlockedTraining"));
  assert.ok(appSource.includes("\"select-unlocked-training\""));
  assert.ok(appSource.includes("\"start-unlocked-training\""));
  assert.ok(appSource.includes("\"apply-guided-practice\""));
  assert.ok(appSource.includes("\"start-guided-practice\""));
  assert.ok(appSource.includes("Review unlocked training first"));
    assert.ok(appSource.includes("Review unlocked preset"));
    assert.ok(appSource.includes("Confidence rising"));
    assert.ok(appSource.includes("Confidence dropped"));
    assert.ok(appSource.includes("Confidence steady"));
    assert.ok(appSource.includes("checkpoint-path-emphasis-copy-"));
  assert.ok(appSource.includes("Follow checkpoint action"));
  assert.ok(appSource.includes("Start checkpoint step"));
  assert.ok(appSource.includes("Apply checkpoint preset"));
  assert.ok(appSource.includes("Apply recovery preset"));
  assert.ok(appSource.includes("Start recovery step"));
  assert.ok(appSource.includes("Apply return preset"));
  assert.ok(appSource.includes("Start return step"));
  assert.ok(appSource.includes("Apply reintegration preset"));
  assert.ok(appSource.includes("Start reintegration step"));
  assert.ok(appSource.includes("Apply promotion preset"));
  assert.ok(appSource.includes("Start promotion step"));
  assert.ok(appSource.includes("Apply mastery preset"));
  assert.ok(appSource.includes("Start mastery step"));
  assert.ok(appSource.includes("Checkpoint ${checkpointLabel}:"));
  assert.ok(appSource.includes("Unlock recap"));
  assert.ok(appSource.includes("Recovery recap"));
  assert.ok(appSource.includes("Return recap"));
  assert.ok(appSource.includes("Reintegration recap"));
  assert.ok(appSource.includes("Promotion recap"));
  assert.ok(appSource.includes("Mastery recap"));
  assert.ok(appSource.includes("buildCheckpointWaitingMessage(\"Checkpoint history snapshots\")"));
  assert.ok(appSource.includes("Terminal mastery active"));
  assert.ok(appSource.includes("Recovery route ->"));
  assert.ok(appSource.includes("Return route ->"));
  assert.ok(appSource.includes("Promotion ->"));
  assert.ok(appSource.includes("Reintegration ->"));
  assert.ok(appSource.includes("applyTrainingSessionPreset"));
  assert.ok(appSource.includes("session form is prefilled"));
  assert.ok(appSource.includes("applied the targeted preset"));
  assert.ok(appSource.includes("applied the default session preset"));
  assert.ok(appSource.includes("Unlocked ${unlockTransition.unlockedTrainingTitles.join(\", \")}"));
  assert.ok(appSource.includes("Unlock onboarding will appear after the next newly unlocked training."));
  assert.ok(appSource.includes("Unlocked because:"));
  assert.ok(appSource.includes("Focus section:"));
  assert.ok(appSource.includes("Session form ready:"));
  assert.ok(appSource.includes("Recommended start: full chart at"));
  assert.ok(appSource.includes("Launch is ready: use Start unlocked training now."));
  assert.ok(appSource.includes("Connect the local engine before launching the unlocked training."));
  assert.ok(appSource.includes("Launching unlocked training:"));
  assert.ok(appSource.includes("buildCheckpointWaitingMessage(\"Session completion recap\")"));
  assert.ok(appSource.includes("buildCheckpointWaitingMessage(\"Progression timeline\")"));
  assert.ok(appSource.includes("No new training unlocks this run."));
  assert.ok(appSource.includes("Next guided step updated to"));
  assert.ok(appSource.includes("Guided next step remains"));
  assert.ok(appSource.includes("Latest session"));
  assert.ok(appSource.includes("Dominant confidence signal"));
    assert.ok(appSource.includes("createDominantConfidenceSignalBadges"));
    assert.ok(appSource.includes("mergeCheckpointBadges"));
    assert.ok(appSource.includes("Dominant signal"));
  assert.ok(appSource.includes("Unlock transition"));
  assert.ok(appSource.includes("Next guided step"));
  assert.ok(appSource.includes("Return Ready"));
  assert.ok(appSource.includes("Return Confirmed"));
  assert.ok(appSource.includes("Full Chart Back"));
  assert.ok(appSource.includes("Promotion Landed"));
  assert.ok(appSource.includes("Ramp Confirmed"));
  assert.ok(appSource.includes("Chain Confirmed"));
  assert.ok(appSource.includes("Chain Graduated"));
  assert.ok(appSource.includes("Terminal Mastery"));
  assert.ok(appSource.includes("Grade ${sessionRecap.grade}"));
  assert.ok(appSource.includes('badge badge-small'));
  assert.ok(stylesSource.includes(".badge-row"));
  assert.ok(stylesSource.includes(".badge-small"));
  assert.ok(stylesSource.includes(".badge-success"));
  assert.ok(stylesSource.includes(".badge-warning"));
  assert.ok(stylesSource.includes(".badge-neutral"));
  assert.ok(stylesSource.includes(".checkpoint-recap-grid"));
  assert.ok(stylesSource.includes(".progression-desktop-layout"));
  assert.ok(stylesSource.includes(".progression-overview-column"));
  assert.ok(stylesSource.includes(".progression-workbench-column"));
  assert.ok(stylesSource.includes(".progression-history-column"));
  assert.ok(stylesSource.includes(".progression-action-column"));
  assert.ok(stylesSource.includes(".progression-column-head"));
  assert.ok(stylesSource.includes(".progression-column-head h3"));
  assert.ok(stylesSource.includes(".progression-rail-section"));
  assert.ok(stylesSource.includes(".progression-rail-next-step"));
  assert.ok(stylesSource.includes(".progression-next-step-stack"));
  assert.ok(stylesSource.includes(".progression-next-step-decision"));
  assert.ok(stylesSource.includes(".progression-next-action-state"));
  assert.ok(stylesSource.includes(".progression-next-step-decision.is-execution-waiting"));
  assert.ok(stylesSource.includes(".progression-next-step-decision.is-execution-blocked"));
  assert.ok(stylesSource.includes(".progression-next-step-decision.is-execution-prepare"));
  assert.ok(stylesSource.includes(".progression-next-step-decision.is-execution-ready"));
  assert.ok(stylesSource.includes(".progression-next-step-rationale"));
  assert.ok(stylesSource.includes(".progression-next-step-cta"));
  assert.ok(stylesSource.includes(".progression-next-action-hint"));
  assert.ok(stylesSource.includes(".progression-next-action-feedback-stack"));
  assert.ok(stylesSource.includes(".progression-next-action-feedback-item"));
  assert.ok(stylesSource.includes(".progression-next-action-feedback-badge-row"));
  assert.ok(stylesSource.includes(".progression-next-action-feedback-item .badge"));
  assert.ok(stylesSource.includes(".progression-next-action-feedback-item .badge-row + .progression-next-action-result"));
  assert.ok(stylesSource.includes(".progression-next-action-feedback-result"));
  assert.ok(stylesSource.includes(".progression-next-action-feedback-label"));
  assert.ok(stylesSource.includes(".progression-next-action-feedback-result .progression-next-action-feedback-label"));
  assert.ok(stylesSource.includes(".progression-next-action-feedback-focus .progression-next-action-feedback-label"));
  assert.ok(stylesSource.includes(".progression-next-action-result"));
  assert.ok(stylesSource.includes(".progression-next-action-focus"));
  assert.ok(stylesSource.includes(".progression-next-action-result.is-feedback-success"));
  assert.ok(stylesSource.includes(".progression-next-action-result.is-feedback-warning"));
  assert.ok(stylesSource.includes(".progression-next-action-focus.is-focus-success"));
  assert.ok(stylesSource.includes(".progression-next-action-focus.is-focus-warning"));
  assert.ok(stylesSource.includes(".progression-next-action-focus.is-target-session-status"));
  assert.ok(stylesSource.includes(".progression-next-action-focus.is-target-checkpoint-detail"));
  assert.ok(stylesSource.includes(".progression-next-step-decision.is-handoff-session-status"));
  assert.ok(stylesSource.includes(".progression-next-step-decision.is-handoff-checkpoint-detail"));
  assert.ok(stylesSource.includes(".progression-next-step-decision.is-handoff-blocked"));
  assert.ok(stylesSource.includes(".progression-next-step-decision.is-handoff-session-status .progression-next-action-feedback-result .progression-next-action-feedback-label"));
  assert.ok(stylesSource.includes(".progression-next-step-decision.is-handoff-checkpoint-detail .progression-next-action-feedback-result .progression-next-action-feedback-label"));
  assert.ok(stylesSource.includes(".progression-next-step-decision.is-handoff-blocked .progression-next-action-feedback-result .progression-next-action-feedback-label"));
  assert.ok(stylesSource.includes("box-shadow: inset 3px 0 0 rgba(180, 79, 32, 0.16);"));
  assert.ok(stylesSource.includes("padding-top: 8px;"));
  assert.ok(stylesSource.includes("border-top: 1px solid rgba(180, 79, 32, 0.08);"));
  assert.ok(stylesSource.includes(".progression-next-step-rationale #dominant-confidence-next-action-status"));
  assert.ok(stylesSource.includes(".progression-next-step-decision #progression-next-action-status"));
  assert.ok(stylesSource.includes("grid-template-columns: minmax(0, 1.2fr) minmax(300px, 0.8fr);"));
  assert.ok(stylesSource.includes("background: rgba(255, 250, 243, 0.78);"));
  assert.ok(stylesSource.includes("box-shadow: inset 0 0 0 1px rgba(255, 255, 255, 0.35);"));
  assert.ok(stylesSource.includes("gap: 10px;"));
  assert.ok(stylesSource.includes("top: 16px;"));
  assert.ok(stylesSource.includes("#progression-checkpoint-history"));
  assert.ok(stylesSource.includes("#progression-timeline"));
  assert.ok(stylesSource.includes("max-block-size: 320px;"));
  assert.ok(stylesSource.includes("min-block-size: 220px;"));
  assert.ok(stylesSource.includes("min-block-size: 180px;"));
  assert.ok(stylesSource.includes("overflow: auto;"));
  assert.ok(stylesSource.includes("padding-top: 12px;"));
  assert.ok(stylesSource.includes("border-top: 1px solid rgba(180, 79, 32, 0.12);"));
  assert.ok(stylesSource.includes("border-top: 1px dashed rgba(180, 79, 32, 0.12);"));
  assert.ok(stylesSource.includes("padding: 12px;"));
  assert.ok(stylesSource.includes("padding: 10px;"));
  assert.ok(stylesSource.includes("border-radius: 14px;"));
  assert.ok(stylesSource.includes("border-radius: 12px;"));
  assert.ok(stylesSource.includes("background: rgba(255, 246, 234, 0.74);"));
  assert.ok(stylesSource.includes("background: rgba(255, 251, 246, 0.92);"));
  assert.ok(stylesSource.includes("box-shadow: inset 0 0 0 1px rgba(180, 79, 32, 0.08);"));
  assert.ok(stylesSource.includes("background: rgba(255, 252, 247, 0.76);"));
  assert.ok(stylesSource.includes("background: rgba(255, 249, 241, 0.92);"));
  assert.ok(stylesSource.includes("border-color: rgba(180, 79, 32, 0.18);"));
  assert.ok(stylesSource.includes(".progression-action-column .status-card"));
  assert.ok(stylesSource.includes("min-height: 58px;"));
  assert.ok(stylesSource.includes(".progression-action-column .checkpoint-detail-badges"));
  assert.ok(stylesSource.includes("margin-top: 0;"));
  assert.ok(stylesSource.includes("#progression-next-action"));
  assert.ok(stylesSource.includes("width: 100%;"));
  assert.ok(stylesSource.includes(".checkpoint-path-summary-grid"));
  assert.ok(stylesSource.includes(".checkpoint-recap-card"));
  assert.ok(stylesSource.includes(".checkpoint-recap-card-confidence-rising"));
  assert.ok(stylesSource.includes(".checkpoint-recap-card-confidence-dropped"));
  assert.ok(stylesSource.includes(".checkpoint-recap-emphasis-copy"));
  assert.ok(stylesSource.includes(".checkpoint-recap-confidence-reason"));
  assert.ok(stylesSource.includes(".checkpoint-recap-confidence-group"));
  assert.ok(stylesSource.includes(".checkpoint-path-summary-card.is-primary"));
  assert.ok(stylesSource.includes(".checkpoint-path-summary-card"));
  assert.ok(stylesSource.includes(".checkpoint-path-summary-card:hover"));
  assert.ok(stylesSource.includes(".checkpoint-path-action-button"));
  assert.ok(stylesSource.includes(".checkpoint-path-feedback"));
  assert.ok(stylesSource.includes(".checkpoint-path-feedback-success"));
  assert.ok(stylesSource.includes(".checkpoint-path-feedback-error"));
  assert.ok(stylesSource.includes(".status-card.is-warning"));
  assert.ok(stylesSource.includes(".status-card-structured"));
  assert.ok(stylesSource.includes(".status-card-structured:hover"));
  assert.ok(stylesSource.includes(".status-card-structured:focus-visible"));
  assert.ok(stylesSource.includes(".status-card-structured.is-active"));
  assert.ok(stylesSource.includes(".status-card-structured.is-spotlight"));
  assert.ok(stylesSource.includes(".status-card-meta"));
  assert.ok(stylesSource.includes("min-inline-size: 0;"));
  assert.ok(stylesSource.includes("margin-bottom: 1px;"));
  assert.ok(stylesSource.includes(".status-card-state"));
  assert.ok(stylesSource.includes("flex: 0 0 auto;"));
  assert.ok(stylesSource.includes(".status-card-state-success"));
  assert.ok(stylesSource.includes(".status-card-state-warning"));
  assert.ok(stylesSource.includes(".status-card-state-error"));
  assert.ok(stylesSource.includes(".status-card-state-neutral"));
  assert.ok(stylesSource.includes(".status-card-flow-summary"));
  assert.ok(stylesSource.includes(".status-card-flow-guidance"));
  assert.ok(stylesSource.includes(".status-card-flow-detail"));
  assert.ok(stylesSource.includes(".status-card-flow-handoff"));
  assert.ok(stylesSource.includes(".status-card-title"));
  assert.ok(stylesSource.includes("line-height: 1.2;"));
  assert.ok(stylesSource.includes(".status-card-source"));
  assert.ok(stylesSource.includes("min-inline-size: 0;"));
  assert.ok(stylesSource.includes(".status-card-source-summary"));
  assert.ok(stylesSource.includes(".status-card-source-guidance"));
  assert.ok(stylesSource.includes(".status-card-source-detail"));
  assert.ok(stylesSource.includes(".status-card-source-handoff"));
  assert.ok(stylesSource.includes(".status-card-source-active"));
  assert.ok(stylesSource.includes(".status-card-source-neutral"));
  assert.ok(stylesSource.includes(".status-card-source-phase-waiting"));
  assert.ok(stylesSource.includes(".status-card-source-phase-active"));
  assert.ok(stylesSource.includes(".status-card-source-phase-spotlight"));
  assert.ok(stylesSource.includes(".status-card-lead"));
  assert.ok(stylesSource.includes(".status-card-note"));
  assert.ok(stylesSource.includes(".status-card-structured.is-spotlight .status-card-note"));
  assert.ok(stylesSource.includes(".status-card-structured.no-note"));
  assert.ok(stylesSource.includes(".status-card-structured.no-note .status-card-title"));
  assert.ok(stylesSource.includes(".status-card-structured.has-note .status-card-note"));
  assert.ok(stylesSource.includes("@media (max-width: 860px)"));
  assert.ok(stylesSource.includes(".status-card-meta {"));
  assert.ok(stylesSource.includes("gap: 6px;"));
  assert.ok(stylesSource.includes(".status-card-structured.is-spotlight"));
  assert.ok(stylesSource.includes(".status-card-source-phase-spotlight"));
  assert.ok(stylesSource.includes(".status-card-source-summary {"));
  assert.ok(stylesSource.includes(".status-card-source-phase-active {"));
  assert.ok(stylesSource.includes("@media (max-width: 560px)"));
  assert.ok(stylesSource.includes(".status-card-structured:hover,"));
  assert.ok(stylesSource.includes("transform: none;"));
  assert.ok(stylesSource.includes("outline-width: 1px;"));
  assert.ok(stylesSource.includes(".status-card-structured.has-note .status-card-meta"));
  assert.ok(stylesSource.includes(".status-card-structured.no-note .status-card-meta"));
  assert.ok(stylesSource.includes("order: 2;"));
  assert.ok(stylesSource.includes("grid-template-columns: auto minmax(0, 1fr);"));
  assert.ok(stylesSource.includes("column-gap: 6px;"));
  assert.ok(stylesSource.includes("row-gap: 4px;"));
  assert.ok(stylesSource.includes("inline-size: 100%;"));
  assert.ok(stylesSource.includes("order: 1;"));
  assert.ok(stylesSource.includes("letter-spacing: 0.06em;"));
  assert.ok(stylesSource.includes("line-height: 1.18;"));
  assert.ok(stylesSource.includes("max-inline-size: 30ch;"));
  assert.ok(stylesSource.includes("order: 3;"));
  assert.ok(stylesSource.includes("order: 4;"));
  assert.ok(stylesSource.includes("line-height: 1.38;"));
  assert.ok(stylesSource.includes("color: rgba(54, 31, 8, 0.92);"));
  assert.ok(stylesSource.includes("max-inline-size: 34ch;"));
  assert.ok(stylesSource.includes("text-wrap: balance;"));
  assert.ok(stylesSource.includes("text-wrap: pretty;"));
  assert.ok(stylesSource.includes(".status-card-structured.has-note .status-card-source"));
  assert.ok(stylesSource.includes("max-inline-size: min(100%, 20ch);"));
  assert.ok(stylesSource.includes("font-size: 10px;"));
  assert.ok(stylesSource.includes("line-height: 1.4;"));
  assert.ok(stylesSource.includes("color: rgba(84, 56, 24, 0.78);"));
  assert.ok(stylesSource.includes("max-inline-size: 34ch;"));
  assert.ok(stylesSource.includes("overflow-wrap: anywhere;"));
  assert.ok(stylesSource.includes(".status-card-structured.has-note"));
  assert.ok(stylesSource.includes("padding: 2px 6px;"));
  assert.ok(stylesSource.includes("box-shadow: inset 0 0 0 1px rgba(165, 94, 16, 0.08);"));
  assert.ok(stylesSource.includes("justify-self: start;"));
  assert.ok(stylesSource.includes(".status-card-structured.is-active .status-card-state"));
  assert.ok(stylesSource.includes(".status-card-structured.is-spotlight .status-card-state"));
  assert.ok(stylesSource.includes(".status-card-structured.is-active .status-card-lead"));
  assert.ok(stylesSource.includes(".status-card-structured.is-spotlight .status-card-lead"));
  assert.ok(stylesSource.includes(".status-card-structured.is-active .status-card-note"));
  assert.ok(stylesSource.includes(".status-card-structured.is-spotlight .status-card-note"));
  assert.ok(stylesSource.includes("box-shadow: inset 0 0 0 1px rgba(165, 94, 16, 0.16);"));
  assert.ok(stylesSource.includes("0 0 0 3px rgba(165, 94, 16, 0.06);"));
  assert.ok(stylesSource.includes("color: rgba(70, 39, 8, 0.95);"));
  assert.ok(stylesSource.includes("color: rgba(79, 44, 8, 0.98);"));
  assert.ok(stylesSource.includes("color: rgba(94, 63, 25, 0.8);"));
  assert.ok(stylesSource.includes("color: rgba(103, 68, 26, 0.84);"));
  assert.ok(stylesSource.includes("letter-spacing: 0.03em;"));
  assert.ok(stylesSource.includes("text-overflow: ellipsis;"));
  assert.ok(stylesSource.includes("white-space: nowrap;"));
  assert.ok(stylesSource.includes("text-decoration-line: underline;"));
  assert.ok(stylesSource.includes("text-decoration-style: dotted;"));
  assert.ok(stylesSource.includes("text-underline-offset: 0.18em;"));
  assert.ok(stylesSource.includes("opacity: 0.48;"));
  assert.ok(stylesSource.includes("opacity: 0.56;"));
  assert.ok(stylesSource.includes("opacity: 0.74;"));
  assert.ok(stylesSource.includes("@media (max-width: 420px)"));
  assert.ok(stylesSource.includes("grid-template-columns: minmax(0, 1fr);"));
  assert.ok(stylesSource.includes(".status-card-structured.has-note .status-card-meta"));
  assert.ok(stylesSource.includes(".status-card-structured.no-note .status-card-meta"));
  assert.ok(stylesSource.includes(".status-card-structured.has-note {"));
  assert.ok(stylesSource.includes("gap: 2px;"));
  assert.ok(stylesSource.includes("grid-column: 1;"));
  assert.ok(stylesSource.includes("max-inline-size: min(100%, 22ch);"));
  assert.ok(stylesSource.includes("max-inline-size: min(100%, 32ch);"));
  assert.ok(stylesSource.includes("max-inline-size: min(100%, 18ch);"));
  assert.ok(stylesSource.includes("max-inline-size: min(100%, 20ch);"));
  assert.ok(stylesSource.includes("margin-top: 0;"));
  assert.ok(stylesSource.includes("max-inline-size: min(100%, 30ch);"));
  assert.ok(stylesSource.includes("display: -webkit-box;"));
  assert.ok(stylesSource.includes("-webkit-box-orient: vertical;"));
  assert.ok(stylesSource.includes("-webkit-line-clamp: 3;"));
  assert.ok(stylesSource.includes("line-clamp: 3;"));
  assert.ok(stylesSource.includes("-webkit-mask-image: linear-gradient(180deg, #000 0%, #000 78%, transparent 100%);"));
  assert.ok(stylesSource.includes("mask-image: linear-gradient(180deg, #000 0%, #000 78%, transparent 100%);"));
  assert.ok(stylesSource.includes(".status-card-structured.is-spotlight .status-card-note"));
  assert.ok(stylesSource.includes("-webkit-line-clamp: 2;"));
  assert.ok(stylesSource.includes("line-clamp: 2;"));
  assert.ok(stylesSource.includes(".status-card-structured.is-active .status-card-note"));
  assert.ok(stylesSource.includes(".status-card-structured.is-active .status-card-lead"));
  assert.ok(stylesSource.includes(".status-card-structured.is-spotlight .status-card-lead"));
  assert.ok(stylesSource.includes("max-inline-size: min(100%, 31ch);"));
  assert.ok(stylesSource.includes("max-inline-size: min(100%, 29ch);"));
  assert.ok(stylesSource.includes("margin-top: 1px;"));
  assert.ok(stylesSource.includes("-webkit-mask-image: linear-gradient(180deg, #000 0%, #000 80%, transparent 100%);"));
  assert.ok(stylesSource.includes("mask-image: linear-gradient(180deg, #000 0%, #000 80%, transparent 100%);"));
  assert.ok(stylesSource.includes("-webkit-mask-image: linear-gradient(180deg, #000 0%, #000 72%, transparent 100%);"));
  assert.ok(stylesSource.includes("mask-image: linear-gradient(180deg, #000 0%, #000 72%, transparent 100%);"));
  assert.ok(stylesSource.includes("opacity: 0.44;"));
  assert.ok(stylesSource.includes("opacity: 0.52;"));
  assert.ok(stylesSource.includes("opacity: 0.7;"));
  assert.ok(stylesSource.includes(".checkpoint-detail-badges"));
  assert.ok(stylesSource.includes(".checkpoint-path-preset-preview"));
  assert.ok(stylesSource.includes(".checkpoint-path-preset-confidence"));
  assert.ok(stylesSource.includes(".checkpoint-path-preset-confidence-success"));
  assert.ok(stylesSource.includes(".checkpoint-path-preset-confidence-neutral"));
  assert.ok(stylesSource.includes(".checkpoint-path-confidence-reason"));
  assert.ok(stylesSource.includes(".checkpoint-path-confidence-group"));
  assert.ok(stylesSource.includes(".checkpoint-path-summary-card-confidence-rising.is-primary"));
  assert.ok(stylesSource.includes(".checkpoint-path-summary-card-confidence-dropped.is-primary"));
  assert.ok(stylesSource.includes(".checkpoint-path-emphasis-copy"));
  assert.ok(stylesSource.includes(".checkpoint-path-confidence-history"));
  assert.ok(stylesSource.includes(".checkpoint-path-confidence-history-list"));
  assert.ok(stylesSource.includes(".checkpoint-path-confidence-history-entry"));
  assert.ok(stylesSource.includes(".checkpoint-path-confidence-history-entry.is-active"));
  assert.ok(stylesSource.includes(".checkpoint-path-preset-diff-label"));
  assert.ok(stylesSource.includes(".checkpoint-path-preset-diff-list"));
  assert.ok(stylesSource.includes("#progression-checkpoint-detail"));
  assert.ok(stylesSource.includes("position: sticky"));
  assert.ok(stylesSource.includes("position: static;"));
  assert.ok(stylesSource.includes(".history-filter"));
  assert.ok(stylesSource.includes(".checkpoint-history-entry"));
  assert.ok(stylesSource.includes(".checkpoint-history-entry.is-active"));
  assert.ok(stylesSource.includes(".checkpoint-history-group"));
  assert.ok(stylesSource.includes(".checkpoint-history-group-head"));
  assert.ok(appSource.includes("renderSessionCaptureRecommendation"));
  assert.ok(appSource.includes("syncPracticePresetControls"));
  assert.ok(appSource.includes("applyDashboardPracticePreset"));
  assert.ok(appSource.includes("getPendingRecoveryRouteContext"));
  assert.ok(appSource.includes("getPendingReturnAttemptContext"));
  assert.ok(appSource.includes("getPendingPromotionLandingContext"));
  assert.ok(appSource.includes("promotionPhase"));
  assert.ok(appSource.includes("promotionRampBaseTempoBpm"));
  assert.ok(appSource.includes("promotionRampTargetTempoBpm"));
  assert.ok(appSource.includes("promotionChainBaseTempoBpm"));
  assert.ok(appSource.includes("promotionChainTargetTempoBpm"));
  assert.ok(appSource.includes("Promotion chain graduation milestone:"));
  assert.ok(appSource.includes("Terminal training mastery:"));
  assert.ok(appSource.includes("Terminal mastery graduation:"));
  assert.ok(appSource.includes("training.access ??"));
  assert.ok(appSource.includes("Load dashboard to see unlock state"));
  assert.ok(appSource.includes("Load dashboard to see unlock requirements"));
  assert.ok(appSource.includes("Locked training"));
  assert.ok(appSource.includes("Locked because"));
  assert.ok(appSource.includes("Access rationale"));
  assert.ok(appSource.includes("How to unlock:"));
  assert.ok(appSource.includes("Unlock progress:"));
  assert.ok(appSource.includes("Prerequisite status:"));
  assert.ok(appSource.includes("Progress unavailable until trainings are loaded."));
  assert.ok(appSource.includes("No prerequisite trainings."));
  assert.ok(appSource.includes('[done]'));
  assert.ok(appSource.includes('[todo]'));
  assert.ok(appSource.includes("Already available for this user."));
  assert.ok(appSource.includes("payload.data.unlockTransition"));
  assert.ok(appSource.includes("New unlocks:"));
  assert.ok(appSource.includes("Content unlocked"));
  assert.ok(appSource.includes("syncTrainingAccessFromDashboard"));
  assert.ok(appSource.includes("Completed sessions:"));
  assert.ok(appSource.includes("Next unlocks:"));
  assert.ok(appSource.includes("Promotion chain track:"));
  assert.ok(appSource.includes("Promotion chain graduation:"));
  assert.ok(appSource.includes("\"chain-validation\""));
  assert.ok(appSource.includes("\"chain-graduation\""));
  assert.ok(appSource.includes("\"terminal-training-mastery\""));
  assert.ok(appSource.includes("\"terminal-mastery-graduated\""));
  assert.ok(appSource.includes("loopRepetitionCount"));
  assert.ok(appSource.includes("loopTempoStepBpm"));
  assert.ok(appSource.includes("refreshSessionCaptureRecommendation"));
  assert.ok(appSource.includes("applyHistoricalCaptureRecommendation"));
  assert.ok(appSource.includes("maybeAutoApplyHistoricalCaptureRecommendation"));
  assert.ok(appSource.includes("saveCapturePreferences"));
  assert.ok(appSource.includes("recordCaptureOverrideIfNeeded"));
  assert.ok(appSource.includes("exportDiagnosticsReport"));
  assert.ok(appSource.includes("createDiagnosticsFilterQuery"));
  assert.ok(appSource.includes("formatSortingLabel"));
  assert.ok(appSource.includes("Stability score"));
  assert.ok(appSource.includes("Start reliability"));
  assert.ok(appSource.includes("Runtime stability"));
  assert.ok(appSource.includes("Recommendation confidence"));
  assert.ok(appSource.includes("Latency fitness"));
  assert.ok(appSource.includes("Signal quality"));
  assert.ok(appSource.includes("Setup actions"));
  assert.ok(appSource.includes("createCapturePathSummary"));
  assert.ok(appSource.includes("findRecommendedCaptureDevice"));
  assert.ok(appSource.includes("resolveCapturePathRecommendation"));
  assert.ok(appSource.includes("getSessionRecommendationSourceReport"));
  assert.ok(appSource.includes("dashboardCaptureOverrides"));
  assert.ok(appSource.includes("dashboardSetupRecommendations"));
  assert.ok(appSource.includes("setupRecommendationFeedbackStatus"));
  assert.ok(appSource.includes("diagnosticsDeviceRecommendations"));
  assert.ok(appSource.includes("diagnosticsDeviceDetail"));
  assert.ok(appSource.includes("diagnosticsRuntimeIssues"));
  assert.ok(appSource.includes("Scored paths:"));
  assert.ok(appSource.includes("diagnosticsSortBy"));
  assert.ok(appSource.includes("diagnosticsRecommendation"));
  assert.ok(appSource.includes("renderDeviceDiagnosticsDetail"));
  assert.ok(appSource.includes("formatIssueStageLabel"));
  assert.ok(appSource.includes("formatSetupRecommendations"));
  assert.ok(appSource.includes("formatSetupRecommendationStatus"));
  assert.ok(appSource.includes("formatSelectionSource"));
  assert.ok(appSource.includes("formatSetupFeedbackSummary"));
  assert.ok(appSource.includes("recordSetupRecommendationUsage"));
  assert.ok(appSource.includes("evaluateSetupRecommendationHistoryEntry"));
  assert.ok(appSource.includes("findSetupRecommendationHistoryEntry"));
  assert.ok(appSource.includes("Technical + setup feedback"));
  assert.ok(appSource.includes("Setup feedback"));
  assert.ok(appSource.includes("loadSelectedDeviceDiagnostics"));
  assert.ok(appSource.includes("applyCaptureRecommendationButton"));
  assert.ok(appSource.includes("autoApplyCaptureRecommendation"));

  console.log("Web smoke test passed.");
} finally {
  await new Promise((resolve, reject) => {
    server.close((error) => {
      if (error) {
        reject(error);
        return;
      }

      resolve();
    });
  });
}
